spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  datasource:
    url: jdbc:postgresql://localhost:5432/CP_Test
    username: postgres
    password: damiane1997
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/CP_Test
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296


gcs:
  bucket:
    name: test_images_project


server:
  port: 8082