server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

# Adding JWT Secret Key Configuration
jwt:
  secret-key: OkvEZ85awEncAr2d3F4z2OTDHRZRyTJdGd0JSwSwSQo=
