
spring:



  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: damiane1997
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/accountdb
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: ACCOUNT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296




server:
  port: 8485

jwt:
  secret-key: OkvEZ85awEncAr2d3F4z2OTDHRZRyTJdGd0JSwSwSQo=